const missingPeopleList = [ 
	{	firstName : "Harold",
		lastName : "Holt",
		dateMissing : new Date(1967,12,17),
		location : "Point Nepean, Victoria, Australia",
		posessions : ["bathing suit (presumably)"],
		gender: "male",
		famousFor: "17th prime minister of Australia",
		disappearanceContext: "Vanished into the sea while swimming.",
		ageAtDisappearance: 59,
	},
	{	firstName : "Sean",
		lastName : "Flynn",
		dateMissing : new Date(1970,4,6),
		location : "Cambodia",
		gender: "male",
		famousFor: "Son of actors, Errol Flynn and Lili Damita",
		disappearanceContext: "Vanished in Cambodia while working as a photojournalist covering the Vietnam War.",
		ageAtDisappearance: 28,
	},
	{	firstName : "Amelia",
		lastName : "Earhart",
		dateMissing : new Date(1937,7,2),
		location : "Over the Pacific",
		gender: "female",
		famousFor: "World Famous Pilot",
		disappearanceContext: "Vanished over the Pacific Ocean during planned trip around the world.",
		ageAtDisappearance: 39,
	}
]

module.exports = missingPeopleList;